package com.example.ui.screens

import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PrescriptionShareScreen(
    onBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val sageDeep = Color(0xFF2C4531)
    val sageLight = Color(0xFFEAF1EC)
    val terracotta = Color(0xFFC96F4A)

    var patientName by remember { mutableStateOf("Jean Mukendi (34 ans)") }
    var diagnostic by remember { mutableStateOf("Grippe A / Fièvre persistante") }
    var med1 by remember { mutableStateOf("Paracétamol 1g") }
    var poso1 by remember { mutableStateOf("1 comprimé 3x/jour") }
    var dur1 by remember { mutableStateOf("5 jours") }
    var isGenerated by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Générer & Partager une Ordonnance", color = Color.White) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Retour", tint = Color.White)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = sageDeep)
            )
        }
    ) { paddingValues ->
        Column(
            modifier = modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(sageLight)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Card(
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White),
                elevation = CardDefaults.cardElevation(defaultElevation = 4.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text("Information de la Prescription", fontWeight = FontWeight.Bold, fontSize = 18.sp, color = sageDeep)

                    OutlinedTextField(
                        value = patientName,
                        onValueChange = { patientName = it },
                        label = { Text("Nom du Patient") },
                        modifier = Modifier.fillMaxWidth()
                    )

                    OutlinedTextField(
                        value = diagnostic,
                        onValueChange = { diagnostic = it },
                        label = { Text("Diagnostic / Motif") },
                        modifier = Modifier.fillMaxWidth()
                    )

                    Text("Prescription Médicamenteuse :", fontWeight = FontWeight.SemiBold, fontSize = 15.sp, color = sageDeep)

                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                        OutlinedTextField(value = med1, onValueChange = { med1 = it }, label = { Text("Médicament") }, modifier = Modifier.weight(2f))
                        OutlinedTextField(value = poso1, onValueChange = { poso1 = it }, label = { Text("Posologie") }, modifier = Modifier.weight(1.5f))
                    }

                    Button(
                        onClick = { isGenerated = true },
                        colors = ButtonDefaults.buttonColors(containerColor = sageDeep),
                        shape = RoundedCornerShape(12.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Icon(Icons.Default.Build, contentDescription = null)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("📄 Générer l'Aperçu PDF & Cachet")
                    }
                }
            }

            if (isGenerated) {
                Card(
                    shape = RoundedCornerShape(16.dp),
                    colors = CardDefaults.cardColors(containerColor = Color.White),
                    elevation = CardDefaults.cardElevation(defaultElevation = 6.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Aperçu du Fichier Ordonnance :", fontWeight = FontWeight.Bold, fontSize = 16.sp, color = sageDeep)

                        Spacer(modifier = Modifier.height(10.dp))

                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(Color(0xFFFAFAFA))
                                .border(1.dp, Color.LightGray, RoundedCornerShape(8.dp))
                                .padding(16.dp)
                        ) {
                            Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                                Text("Dr. Kabange Mwangele — Cardiologue", fontWeight = FontWeight.Bold, color = sageDeep)
                                Text("RPPS : 1092837492 • Contact : henockaduma2@gmail.com", fontSize = 12.sp, color = Color.Gray)
                                Divider(modifier = Modifier.padding(vertical = 4.dp))
                                Text("Patient : $patientName", fontWeight = FontWeight.Medium)
                                Text("Diagnostic : $diagnostic", fontSize = 14.sp)
                                Text("Traitement : $med1 — $poso1 ($dur1)", fontWeight = FontWeight.Bold, color = sageDeep)
                                Spacer(modifier = Modifier.height(12.dp))
                                Row(horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) {
                                    Text("📜 Cachet Officiel Médical", fontSize = 11.sp, color = sageDeep)
                                    Text("✍️ Signature Numérique", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = sageDeep)
                                }
                            }
                        }

                        Spacer(modifier = Modifier.height(16.dp))

                        Text("Partager par :", fontWeight = FontWeight.Bold, fontSize = 14.sp, color = sageDeep)
                        Spacer(modifier = Modifier.height(8.dp))

                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                            Button(
                                onClick = { Toast.makeText(context, "Ordonnance partagée dans la messagerie !", Toast.LENGTH_SHORT).show() },
                                colors = ButtonDefaults.buttonColors(containerColor = sageDeep),
                                modifier = Modifier.weight(1f)
                            ) {
                                Text("💬 Messagerie", fontSize = 12.sp)
                            }

                            Button(
                                onClick = { Toast.makeText(context, "Email envoyé avec copie à henockaduma2@gmail.com", Toast.LENGTH_SHORT).show() },
                                colors = ButtonDefaults.buttonColors(containerColor = terracotta),
                                modifier = Modifier.weight(1f)
                            ) {
                                Text("📧 Email", fontSize = 12.sp)
                            }
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                            OutlinedButton(
                                onClick = { Toast.makeText(context, "SMS avec lien sécurisé envoyé au patient !", Toast.LENGTH_SHORT).show() },
                                modifier = Modifier.weight(1f)
                            ) {
                                Text("📱 SMS", fontSize = 12.sp)
                            }

                            OutlinedButton(
                                onClick = { Toast.makeText(context, "PDF Téléchargé dans les fichiers !", Toast.LENGTH_SHORT).show() },
                                modifier = Modifier.weight(1f)
                            ) {
                                Text("💾 Télécharger PDF", fontSize = 12.sp)
                            }
                        }
                    }
                }
            }
        }
    }
}
